spring:
  application:
    name: sc-businesses-manager-api
  datasource:
    url: jdbc:postgresql://localhost:5432/scbusiness
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.scbusinesses: INFO
    org.springframework.web: WARN