INSERT INTO businesses (id, name, owner_name, city, segment, contact, status)
VALUES ('BUS001', 'TechNova Soluções', 'Carlos Eduardo Mendes', 'São Paulo', 'TECHNOLOGY',
        'carlos.mendes@technova.com.br', 'ACTIVE'),
       ('BUS002', 'AgroVerde Produções', 'Maria Aparecida Silva', 'Ribeirão Preto', 'AGRIBUSINESS', '(16) 99234-5678',
        'ACTIVE'),
       ('BUS003', 'Comercial Ponto Certo', 'João Batista Oliveira', 'Belo Horizonte', 'COMMERCE',
        'joao@pontocerto.com.br', 'ACTIVE'),
       ('BUS004', 'Indústria Metalfort', 'Roberto Ferreira Costa', 'Santo André', 'INDUSTRY', '(11) 3456-7890',
        'INACTIVE'),
       ('BUS005', 'ServiMax Consultoria', 'Ana Paula Rodrigues', 'Curitiba', 'SERVICES',
        'ana.rodrigues@servimax.com.br', 'ACTIVE'),
       ('BUS006', 'DataBridge Tecnologia', 'Felipe Augusto Lima', 'Florianópolis', 'TECHNOLOGY', '(48) 99876-5432',
        'ACTIVE'),
       ('BUS007', 'Fazenda Boa Esperança', 'Antônio Carlos Souza', 'Goiânia', 'AGRIBUSINESS',
        'antonio@fazendaboa.com.br', 'ACTIVE'),
       ('BUS008', 'Supermercados FreshMart', 'Patrícia Helena Nunes', 'Porto Alegre', 'COMMERCE', '(51) 3321-4567',
        'ACTIVE'),
       ('BUS009', 'Fábrica Têxtil Rosário', 'Marcos Vinícius Alves', 'Fortaleza', 'INDUSTRY',
        'marcos.alves@textilrosario.com.br', 'INACTIVE'),
       ('BUS010', 'Clínica Bem Estar', 'Juliana Cristina Pinto', 'Brasília', 'SERVICES', '(61) 98765-1234', 'ACTIVE'),
       ('BUS011', 'CodeSphere Sistemas', 'Ricardo Henrique Braga', 'Recife', 'TECHNOLOGY', 'ricardo@codesphere.com.br',
        'ACTIVE'),
       ('BUS012', 'Cerealista Campo Aberto', 'Luiz Fernando Teixeira', 'Campo Grande', 'AGRIBUSINESS',
        '(67) 99123-4567', 'ACTIVE'),
       ('BUS013', 'Loja Casa & Estilo', 'Fernanda Beatriz Moura', 'Salvador', 'COMMERCE', 'fernanda@casaestilo.com.br',
        'INACTIVE'),
       ('BUS014', 'Metalúrgica Precisa', 'Gustavo Henrique Ramos', 'Contagem', 'INDUSTRY', '(31) 3456-8901', 'ACTIVE'),
       ('BUS015', 'Logística Veloz', 'Camila Souza Barbosa', 'Manaus', 'SERVICES', 'camila@logisticaveloz.com.br',
        'ACTIVE'),
       ('BUS016', 'Nexus Cloud Soluções', 'Bruno Alexandre Dias', 'Campinas', 'TECHNOLOGY', '(19) 99654-3210',
        'ACTIVE'),
       ('BUS017', 'Granja São Francisco', 'Sebastião Melo Cardoso', 'Uberlândia', 'AGRIBUSINESS',
        'sebastiao@granjasf.com.br', 'INACTIVE'),
       ('BUS018', 'Distribuidora MegaFlex', 'Vanessa Oliveira Cunha', 'Natal', 'COMMERCE', '(84) 98877-6655', 'ACTIVE'),
       ('BUS019', 'Plásticos Induflex', 'Leandro Martins Vieira', 'Caxias do Sul', 'INDUSTRY',
        'leandro@induflex.com.br', 'ACTIVE'),
       ('BUS020', 'RH Estratégico', 'Daniela Ferraz Monteiro', 'São Paulo', 'SERVICES', '(11) 97788-9900', 'ACTIVE');